### ISSUE TITLE
Error when running task

### ISSUE THREAD

**Issue by Ushimaster** [colindembovsky/cols-agent-tasks#50] opened 2017-03-01 16:20 UTC
Got this in error in the TFS 2015 Update 2 Release Management:

2017-03-01T16:17:39.3689667Z C:\Build Agents\default\tasks\JSONTokenizer\0.0.83\tokenizer.js:10
 
2017-03-01T16:17:39.3689667Z const tl = require("vsts-task-lib/task");
 
2017-03-01T16:17:39.3699665Z ^^^^^
 
2017-03-01T16:17:39.3699665Z SyntaxError: Use of const in strict mode.
 
2017-03-01T16:17:39.3709639Z     at exports.runInThisContext (vm.js:73:16)
 
2017-03-01T16:17:39.3709639Z     at Module._compile (module.js:443:25)
 
2017-03-01T16:17:39.3719623Z     at Object.Module._extensions..js (module.js:478:10)
 
2017-03-01T16:17:39.3719623Z     at Module.load (module.js:355:32)
 
2017-03-01T16:17:39.3729622Z     at Function.Module._load (module.js:310:12)
 
2017-03-01T16:17:39.3729622Z     at Function.Module.runMain (module.js:501:10)
 
2017-03-01T16:17:39.3739615Z     at startup (node.js:129:16)
 
2017-03-01T16:17:39.3739615Z     at node.js:814:3

**Comment by colindembovsky** [comment] 2017-03-01 17:38
This is a duplicate of #40 - looks like you need to update your node version.

**Closed by colindembovsky** 2017-03-01 17:38 UTC
Labels: duplicate

**Comment by Ushimaster** [comment] 2017-03-03 14:21
The version of my Node is 7.7.1
