### ISSUE TITLE
Cannot find module 'vso-task-lib'

### ISSUE THREAD

**Issue by GeirFrimann** [colindembovsky/cols-agent-tasks#4] opened 2016-02-19 19:45 UTC
Installed the extension from the VSTS marketplace (no mentions of dependencies), got the following error message the first time I tried to use it:
2016-02-19T19:07:05.1093348Z Set workingFolder to default: D:\Agent\tasks\ReplaceTokens\0.0.3
2016-02-19T19:07:05.3121387Z module.js:338 
2016-02-19T19:07:05.3121387Z     throw err;
2016-02-19T19:07:05.3121387Z           ^
2016-02-19T19:07:05.3121387Z Error: Cannot find module 'vso-task-lib'
2016-02-19T19:07:05.3121387Z     at Function.Module._resolveFilename (module.js:336:15)
2016-02-19T19:07:05.3121387Z     at Function.Module._load (module.js:278:25)
2016-02-19T19:07:05.3121387Z     at Module.require (module.js:365:17)
2016-02-19T19:07:05.3121387Z     at require (module.js:384:17)
2016-02-19T19:07:05.3121387Z     at Object.<anonymous> (D:\Agent\tasks\ReplaceTokens\0.0.3\replaceTokens.js:1:72)
2016-02-19T19:07:05.3121387Z     at Module._compile (module.js:460:26)
2016-02-19T19:07:05.3121387Z     at Object.Module._extensions..js (module.js:478:10)
2016-02-19T19:07:05.3121387Z     at Module.load (module.js:355:32)
2016-02-19T19:07:05.3121387Z     at Function.Module._load (module.js:310:12)
2016-02-19T19:07:05.3121387Z     at Function.Module.runMain (module.js:501:10)

**Comment by colindembovsky** [comment] 2016-02-22 08:00
Duplicate of #3

**Closed** 2016-02-22 08:01 UTC
